### ISSUE TITLE
Game not found on C:

### ISSUE THREAD

**Issue by hievor** [FlorianFFF/RT3Multiplayer#1]
I installed the Game on another drive than C: (main disk is full most times also I seperated them) + it's the steam version , so it always will be installed on Drive : \ steamlibrary
i tried symlink and similar but this did not work out

it's showing in the multiplayer client it can't find the game

is there any way to direct the multiplayer client to another directory like in the config file?
would be awesome to also see this beeing added when it's not finding the game to manually direct it to the directory

**Comment by FlorianFFF** [comment]
Yes this is possible!
You should edit the (or create) the following config file:
`%appdata%\Railroad Tycoon 3 Multiplayer Client\config.json`
Open this file with a text editor and replace the content of the file by the following:
`{"ver":"v1.0","gamefile":"C:\\Program Files (x86)\\Steam\\steamapps\\common\\Railroad Tycoon 3\\RT3_mp.exe","gamefolder":"C:\\Program Files (x86)\\Steam\\steamapps\\common\\Railroad Tycoon 3\\"}`
Where you change C:\\ by the drive you want to use, like D:\\. 
Note: Make sure to edit both the gamefile and the gamefolder path!

**Comment by hievor** [comment]
worked thx!
i just had to change RT3_Mp.exe to RT3.exe ,  before that it hung at hosting game...please wait
so my config.json looks now working like this:
{"ver":"v1.0","gamefile":"G:\\Steam\\steamapps\\common\\Railroad Tycoon 3\\RT3.exe","gamefolder":"G:\\Steam\\steamapps\\common\\Railroad Tycoon 3\\","username":"whateveryournameis"}
